/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;
import DAO.*;
import DTO.*;
import NEGOCIO.Excel;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.*;
import org.apache.log4j.Logger;
//branch principal

/**
 *
 * @author Yoyin
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    private final static Logger log = Logger.getLogger(VistaPrincipal.class);
    int joption = 0;
    
    
    public VistaPrincipal() {
        initComponents();
        this.setTitle("INFORME VELOCIDADES");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(icon().getImage());
        log.trace("INICIO APLICACION");
        txtYo.setText("Hecho por Rodrigo Sanchez");
        
    }
    
    private ImageIcon icon()
    {
        ImageIcon img = new ImageIcon(getClass().getResource("/IMAGENES/sice.jpg"));
        ImageIcon imgg = new ImageIcon(img.getImage().getScaledInstance(30, 30, java.awt.Image.SCALE_SMOOTH));
        return imgg;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInforme = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCalMes = new com.toedter.calendar.JMonthChooser();
        jCalAno = new com.toedter.calendar.JYearChooser();
        txtYo = new javax.swing.JLabel();
        lblHojas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIni = new javax.swing.JTextField();
        txtFin = new javax.swing.JTextField();
        rbtTodos = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInforme.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        btnInforme.setText("GENERAR");
        btnInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel1.setText("INFORME DE VELOCIDADES MINUTALES.");

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel2.setText("FECHA:");

        txtYo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txtYo.setForeground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel3.setText("HOJAS");

        txtIni.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        txtFin.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N

        rbtTodos.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        rbtTodos.setText("TODOS");

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel4.setText("INICIO");

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        jLabel5.setText("FIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtYo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtTodos)
                            .addComponent(btnInforme)))
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnInforme, jCalAno, jCalMes, jLabel2, jLabel3, jLabel4, jLabel5, lblHojas, rbtTodos, txtFin, txtIni});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jCalAno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnInforme))
                    .addComponent(jCalMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHojas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(txtYo, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnInforme, jCalAno, jCalMes, jLabel2, jLabel3, jLabel4, jLabel5, lblHojas, rbtTodos, txtFin, txtIni});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeActionPerformed
        
        
        joption = JOptionPane.showConfirmDialog(null, "DESEA INICIAR EL INFORME"
                ,"INICIO INFORME", JOptionPane.YES_NO_OPTION, WIDTH, icon());
        
        if(joption == JOptionPane.YES_OPTION)
        {
            log.trace("-------------------> Iniciar generacion de informe");
        
        
        XSSFWorkbook libro = null;
        XSSFWorkbook wb = null;
        ArrayList<HojaDto> hojas = null;
        
        try{
            if(rbtTodos.isSelected())
            {
                hojas = HojaDao.ObtenerHojas();
            }else
            {
                hojas = HojaDao.ObtenerHojasRango(Integer.parseInt(txtIni.getText()), Integer.parseInt(txtFin.getText()));
            }
                
                int cant = hojas.size();
                lblHojas.setText("Cantidad de Hojas " + cant);
                
//            } catch(Exception e){
//                log.fatal(e);
//                JOptionPane.showMessageDialog(null, "ERROR AL GENERAR EL INFORME\n" + e,"ERROR",WIDTH, icon());
//            }
//        try {
                libro = Excel.abrirXlsx();
            } catch (Exception ex) 
            {
                JOptionPane.showMessageDialog(null, "ERROR AL GENERAR EL INFORME\n" + ex,"ERROR",WIDTH, icon());
                log.fatal(ex);
            }
            
            try{
                for(HojaDto d : hojas)
                {
                    d.setAno(jCalAno.getYear());
                    d.setMes(jCalMes.getMonth() + 1);
                    if(d.getMes() < 10)
                    {
                        d.setTabla(d.getTabla() + d.getAno() + "_0" + d.getMes() + "_01");
                    }else
                    {
                        d.setTabla(d.getTabla() + d.getAno() + "_" + d.getMes() + "_01");
                    }
                    
                    ArrayList<InformeRow> list = InformeRowDao.ObtenerInfome(d);
                    
                    wb = Excel.escribirExcel(libro, list, d.getNombre());
                    list = null;
                    System.gc();
                }
            } catch (Exception ex){
                log.fatal(ex);
                JOptionPane.showMessageDialog(null, "ERROR AL GENERAR EL INFORME\n" + ex,"ERROR",WIDTH, icon());
            }
                if(wb != null)
                {
                    try
                    {
                        String doc = Excel.guardarXlsx(wb);
        
                        btnInforme.setEnabled(true);
                        jCalAno.setEnabled(true);
                        jCalMes.setEnabled(true);
                        int opDoc = JOptionPane.showConfirmDialog(null, "INFORME GENERADO CORRECTAMENTE\n"
                                + "DESEA ABRIR EL DOCUMENTO"
                                ,"EXCEL GENERADO", JOptionPane.YES_NO_OPTION,WIDTH, icon());
                        if(opDoc == JOptionPane.YES_OPTION)
                        {
                            try{
                                Desktop.getDesktop().open(new File(doc));
                            } catch (Exception e){
                                log.fatal(e);
                                JOptionPane.showMessageDialog(null, "ERROR AL GENERAR EL INFORME\n" + e,"ERROR",WIDTH, icon());
                            }
                        }
                    } 
                    catch (IOException | HeadlessException ex)
                    {
                        log.fatal(ex);
                        JOptionPane.showMessageDialog(null, "ERROR AL GENERAR EL INFORME\n" + ex,"INFO",WIDTH, icon());
                    }
                }
        
        
        log.trace("----------------> FIN <-----------------------------------");
    
        }
    }//GEN-LAST:event_btnInformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInforme;
    private com.toedter.calendar.JYearChooser jCalAno;
    private com.toedter.calendar.JMonthChooser jCalMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHojas;
    private javax.swing.JRadioButton rbtTodos;
    private javax.swing.JTextField txtFin;
    private javax.swing.JTextField txtIni;
    private javax.swing.JLabel txtYo;
    // End of variables declaration//GEN-END:variables
}
